title: LD4 Art & Design Affinity Group
description: A community of practice for linked data in art and design contexts from a library- and archives-led perspective

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
